version: "3.7"

services:
    app:
        container_name: '${PROJECT_NAME}-app'
        build:
            context: './'
            args:
                TZ: '${TZ}'
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
        environment:
            TZ: '${TZ}'
        networks:
            - 'app-network'

    db:
        container_name: '${PROJECT_NAME}-db'
        image: mariadb:latest
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
            TZ: '${TZ}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
#        volumes:
#            - dbdata:/var/lib/mysql
        networks:
            - 'app-network'

    phpmyadmin:
        container_name: '${PROJECT_NAME}-phpmyadmin'
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            TZ: '${TZ}'
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            UPLOAD_LIMIT: 300M
        networks:
            - 'app-network'

networks:
    app-network:
        name: 'movies-network'
        driver: bridge

